version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          name: "Build Project"
          command: "yarn build"
      - run:
          name: "Deploy to Digital ocean"
          command: "run: scp -o StrictHostKeyChecking=no -r ./build/* root@165.22.216.78:/var/www/html/hello-world/build/"
